### ISSUE TITLE
build.sbt fails to load with unicode line separator (U+2028)

### ISSUE THREAD

**Issue by mikebridge** [manuelbernhardt/reactive-mentions#1]
running `activator`/`sbt` on a freshly cloned repo gives

``` bash
[error] [/home/bridge/work/reactive-mentions/build.sbt]:38: illegal character '\u2028'
```

Removing the unicode character seems to fix it.

**Comment by manuelbernhardt** [comment]
@mikebridge ugh, thanks for spotting! last minute additions always have a nasty side effect...

**Comment by mikebridge** [comment]
:+1: great book, by the way!

**Comment by manuelbernhardt** [comment]
thanks! the print version should come out in not too much time!
